### ISSUE TITLE
Move to "latest", not "nightlies"

### ISSUE THREAD

**Issue by gabrielwhite** [ferdium/homebrew-ferdium#44]
Now that Ferdium has stable releases, can this cask move to updating only when there is a new "latest" stable release?

Thanks!

**Comment by vraravam** [comment]
This tap repo has 3 casks - one each for the nightly, beta and stable releases. Please refer to the one that you want. Closing.

**Comment by gabrielwhite** [comment]
I'm confused then - who is contributing to the main ferdium cask on brew? It keeps updating to nightlife.

**Comment by vraravam** [comment]
Not sure - but, we are hosting the tap in our git repo. We have new nightlies that came after the stable release. If you are seeing the in-app updater experience, and want to remain on the stable, then you would need to uncheck `View > Preferences > Updates > Include Pre-releases` option.

**Comment by gabrielwhite** [comment]
Solved here: https://github.com/Homebrew/homebrew-cask/pull/128541

Thanks.
